repos:
-   repo: local
    hooks:
    -   id: brew-bundle-dump
        name: Update Brewfile
        entry: bash -c 'brew bundle dump --force && git add Brewfile'
        language: system
        pass_filenames: false
        stages: [pre-commit] 