#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "No arguments supplied"
  exit 1
fi

if [[ $1 == 'feat' ]] || [[ $1 == 'fix' ]] || [[ $1 == 'docs' ]] || [[ $1 == 'style' ]] || [[ $1 == 'refactor' ]] || [[ $1 == 'perf' ]] || [[ $1 == 'test' ]] || [[ $1 == 'chore' ]] || [[ $1 == 'revert' ]]; then
  echo "Conventional commit"
  g commit -m "$1 $2"
  exit 0
fi

if [[ $1 == 'feat(' ]] || [[ $1 == 'fix(' ]] || [[ $1 == 'docs(' ]] || [[ $1 == 'style(' ]] || [[ $1 == 'refactor(' ]] || [[ $1 == 'perf(' ]] || [[ $1 == 'test(' ]] || [[ $1 == 'chore(' ]] || [[ $1 == 'revert(' ]]; then
  echo "Conventional commit with scope"
  g commit -m "$1 $2"
  exit 0
fi

if [[ $1 == 'feat!' ]] || [[ $1 == 'fix!' ]] || [[ $1 == 'docs!' ]] || [[ $1 == 'style!' ]] || [[ $1 == 'refactor!' ]] || [[ $1 == 'perf!' ]] || [[ $1 == 'test!' ]] || [[ $1 == 'chore!' ]] || [[ $1 == 'revert!' ]]; then
  echo "Conventional commit with breaking change"
  g commit -m "$1 $2"
  exit 0
fi

if [[ $1 == 'feat!(' ]] || [[ $1 == 'fix!(' ]] || [[ $1 == 'docs!(' ]] || [[ $1 == 'style!(' ]] || [[ $1 == 'refactor!(' ]] || [[ $1 == 'perf!(' ]] || [[ $1 == 'test!(' ]] || [[ $1 == 'chore!(' ]] || [[ $1 == 'revert!(' ]]; then
  echo "Conventional commit with breaking change and scope"
  g commit -m "$1 $2"
  exit 0
fi

# Not conventional commit

echo "Not conventional commit"

g commit -m "$1"