#!/bin/bash

entry_name="$1"
account="$entry_name"

if ! password=$(security find-generic-password -l "$entry_name" -a "$account" -w | tr -d '\n'); then
  echo "could not get password, error $?"
  exit 1
fi

unset entry_name
unset account

echo "password: $password"