#!/bin/bash
#
# macOS Settings Configuration Script
# Generated by dump-macos-settings
# Date: 2025-10-22 20:58:08
#
# This script configures macOS system preferences to match the source system.
# Review this script before running it!

# Ask for administrator password upfront
sudo -v

# Keep-alive: update existing sudo time stamp until script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo "Applying macOS settings..."

###############################################################################
# System Information                                                          #
###############################################################################

# Computer Name
MACHINE_NAME="Naboo"

sudo scutil --set ComputerName "${MACHINE_NAME}"
sudo scutil --set HostName "${MACHINE_NAME}"
sudo scutil --set LocalHostName "${MACHINE_NAME}"

###############################################################################
# Global Preferences                                                          #
###############################################################################

# Keyboard & Input
# Key repeat rate
defaults write NSGlobalDomain KeyRepeat -int 2

# Initial key repeat delay
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Press and hold for accents
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Show all file extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Trackpad
# Tap to click
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

# Tap to click (multitouch)
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true

# Three finger drag
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool true

# Three finger drag (bluetooth)
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool true

###############################################################################
# Finder                                                                      #
###############################################################################

# Show hidden files
defaults write com.apple.finder AppleShowAllFiles -bool true

# Show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Keep folders on top
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Default view style
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Extension change warning
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Show POSIX path in title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# No .DS_Store on network
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# No .DS_Store on USB
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

###############################################################################
# Dock                                                                        #
###############################################################################

# Dock position
defaults write com.apple.dock orientation -string "bottom"

# Auto-hide Dock
defaults write com.apple.dock autohide -bool true

# Translucent hidden apps
defaults write com.apple.dock showhidden -bool true

# Show recent apps
defaults write com.apple.dock show-recents -bool false

# Dock icon size
defaults write com.apple.dock tilesize -int 74

# Minimize to app icon
defaults write com.apple.dock minimize-to-application -bool true

# Show app indicators
defaults write com.apple.dock show-process-indicators -bool true

###############################################################################
# Safari                                                                      #
###############################################################################

###############################################################################
# Terminal                                                                    #
###############################################################################

# Secure keyboard entry
defaults write com.apple.terminal SecureKeyboardEntry -bool true

###############################################################################
# Mail                                                                        #
###############################################################################

###############################################################################
# Screenshots                                                                 #
###############################################################################

# Screenshot save location
defaults write com.apple.screencapture location -string "/Users/bruno/Desktop"

# Screenshot format
defaults write com.apple.screencapture type -string "png"

# Disable window shadows
defaults write com.apple.screencapture disable-shadow -bool true

###############################################################################
# Time Machine                                                                #
###############################################################################

# Don't prompt for new disks
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

###############################################################################
# App Store                                                                   #
###############################################################################

# Automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Update check frequency
defaults write com.apple.SoftwareUpdate ScheduleFrequency -bool true

# Auto download updates
defaults write com.apple.SoftwareUpdate AutomaticDownload -bool true

# Auto install security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -bool true

###############################################################################
# Photos                                                                      #
###############################################################################

# Prevent Photos from auto-opening
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

###############################################################################
# Energy & Display                                                            #
###############################################################################

# Current power management settings:
# System-wide power settings:
# Currently in use:
#  standby              1
#  Sleep On Power Button 1
#  hibernatefile        /var/vm/sleepimage
#  powernap             1
#  networkoversleep     0
#  disksleep            10
#  sleep                0 (sleep prevented by sharingd, powerd, runningboardd)
#  hibernatemode        3
#  ttyskeepawake        1
#  displaysleep         10
#  tcpkeepalive         1
#  powermode            2
#  womp                 1

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "Dock" "Finder" "Mail" "Photos" "Safari" "SystemUIServer" "Terminal"; do
    killall "${app}" >/dev/null 2>&1 || true
done

echo "Done. Note that some of these changes require a logout/restart to take effect."
