#!/bin/bash

if ! command -v periphery &> /dev/null; then
    echo -e "${RED}Periphery not found. Please install it with 'brew install periphery'${NC}"
    read -p "Would you like to install Periphery now? (y/n) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        brew install periphery
    else
        exit 1
    fi
    exit 1
fi

folder_name="$(basename "$(pwd)")"

xcodebuild \
    -scheme "$folder_name" \
    -destination 'platform=iOS Simulator,OS=18.2,name=iPhone 16' \
    -derivedDataPath ~/Desktop/dd \
    clean build

periphery scan \
    --skip-build \
    --index-store-path ~/Desktop/dd/Index.noindex/DataStore/ \
    --retain-public true \
    --targets "$folder_name"

rm -rf ~/Desktop/dd