#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Bruno Gama <bgamap@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

alias k='pkill -9 -fi'
alias flushdns='sudo killall -HUP mDNSResponder;say flushed'
alias degit="find . -name '.git' -exec rm -rf {} \;"
alias oo="o ."
alias ttl='ping www.google.com'
alias tml='tmux list-sessions'
alias mux='tmuxinator'
alias cask='brew cask'
alias gitk='/usr/bin/wish $(which gitk)'
# Adds colors to cat
alias ccat='pygmentize -g'

# load custom executable functions
for function in ~/.dotfiles/functions/*; do
	source $function
done
