DEFAULT_USER='windu'

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


source "${ZDOTDIR:-$HOME}/.dotfiles/bg_setup.zsh"


PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
