#!/bin/bash

source ${HOME}/.config/bin/prints
pgreen "Starting ${BLUE}${0}"

# Get list of Swift files that are staged for commit
SWIFT_FILES=$(git diff --cached --name-only --diff-filter=d | grep "\.swift$" || true)

if [ -z "$SWIFT_FILES" ]; then
    echo -e "${GREEN}No Swift files to check${NC}"
    exit 0
fi

# Check if swiftlint is installed
$HOME/.config/bin/check-dependency swiftlint

# Run SwiftLint

LINT_PASS=true

pwarning "Running ${BLUE}\"SwiftLint\"${NC}${YELLOW}..."
for file in $SWIFT_FILES; do
    if [ -f "$file" ]; then
        LINT_RESULT=$(swiftlint lint "$file" 2>&1)
        if [ $? -ne 0 ]; then
            perror "SwiftLint failed for ${BLUE}\"$file\""
            echo "$LINT_RESULT"
            LINT_PASS=false
        fi
    fi
done

if [ "$LINT_PASS" = false ]; then
    perror "Please fix ${BLUE}\"SwiftLint\"${NC}${RED} issues before committing."
    exit 1
fi

psuccess "Swift SwiftLint pre-commit hook completed successfully"
exit 1