#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
install findutils

# Install updated zsh version
install zsh


# Install wget with IRI support
install wget --enable-iri


install ack

install gettext

install git

install imagemagick

install man2html

install mercurial

install multimarkdown

install node

install siege

install sip

install unrar

install wget

install axel

install mogenerator

install the_silver_searcher

install tig

install webkit2png

tap homebrew/versions
install lua52

# Remove outdated versions from the cellar
cleanup