#
installcask Install
installcask native
installcask apps
brew install phinze/cask/brew-cask
brew tap caskroom/versions

function installcask() {
	brew cask install "${@}" 2> /dev/null
}

installcask dropbox
installcask google-chrome
installcask google-chrome-canary
installcask imagealpha
installcask imageoptim
installcask iterm2
installcask macvim
installcask miro-video-converter
installcask opera
installcask opera-developer
installcask opera-next
installcask sublime-text
installcask the-unarchiver
installcask tor-browser
installcask transmission
installcask ukelele
installcask virtualbox
installcask vlc

# QuickLook Plugins
installcask qlcolorcode
installcask qlstephen
installcask qlmarkdown
installcask quicklook-json
installcask qlprettypatch
installcask quicklook-csv
installcask betterzipql
installcask webp-quicklook
installcask suspicious-package